export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

